# Generated by Django 3.2.7 on 2021-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelname', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Ram', models.FloatField()),
                ('Rom', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Processor', models.CharField(max_length=5)),
                ('document', models.FileField(upload_to='document/')),
            ],
        ),
    ]
