# Generated by Django 3.2.7 on 2021-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
